### ISSUE TITLE
Touch Event // Webkit

### ISSUE THREAD

**Issue by TonySma** [noraesae/perfect-scrollbar#524]
Hello,

I have a problem using perfectScrollbar on mobile browser using webkit. 
When i swipe on the container of the scrollbar, nothing move, the swipePropagation option seems not working. 
Same problem with G Chrome dev toolbar in mobile view. 

Work well in firefox. 

You can check it here : https://jsfiddle.net/gg99a1ge/2/

Thanks for your help

**Comment by noraesae** [comment]
I have just tried and it seems working well in both iOS Safari and Google Chrome devtool. Can you explain the problem more specifically?

**Comment by maximeloizeau** [comment]
I also noticed this issue but on Safari 8 only, when scrolling with the touchpad.

**Comment by TonySma** [comment]
Hello,
Problem solved by remplacing 
@mixin ps-container($theme) {
  -ms-touch-action: none;
  touch-action: none;
  overflow: hidden !important;
  -ms-overflow-style: none;

by 
@mixin ps-container($theme) {
  overflow: hidden !important;
  -ms-overflow-style: none;

**Comment by megapctr** [comment]
@noraesae the problem is still present on 0.6.12, and patch from @TonySma solves it.

In my case, the problem happens when the container is big enough not to require a scrollbar. When the container is smaller and requires the scrollbar, scrolling works fine.

**Comment by megapctr** [comment]
Just to be sure, when testing in chrome dev tools, you have to click and drag to emulate a touch swipe.
